//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcLibreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionSet
    {
        public int Id { get; set; }
        public string ClienteID { get; set; }
        public string Sector { get; set; }
        public string Pais { get; set; }
        public string Calle { get; set; }
        public string Provincia { get; set; }
    
        public virtual ClientesSet ClientesSet { get; set; }
    }
}
