//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcLibreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialPrestamoSet
    {
        public int Id { get; set; }
        public string LibroEjemplarCodigo { get; set; }
        public string ClientesIdentificacion { get; set; }
        public Nullable<System.DateTime> Fecha_Ini { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
        public int Estado { get; set; }
    
        public virtual ClientesSet ClientesSet { get; set; }
        public virtual LibroEjemplarSet LibroEjemplarSet { get; set; }
    }
}
