//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcLibreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroEjemplarSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LibroEjemplarSet()
        {
            this.HistorialPrestamoSets = new HashSet<HistorialPrestamoSet>();
        }
    
        public string Codigo { get; set; }
        public string LibroISBN { get; set; }
        public int Numero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialPrestamoSet> HistorialPrestamoSets { get; set; }
        public virtual LibrosSet LibrosSet { get; set; }
    }
}
