//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcLibreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibrosSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LibrosSet()
        {
            this.LibroAutorSets = new HashSet<LibroAutorSet>();
            this.LibroEjemplarSets = new HashSet<LibroEjemplarSet>();
        }
    
        public string ISBN { get; set; }
        public string Titulo { get; set; }
        public string Pais { get; set; }
        public int Stock { get; set; }
        public string Editorial { get; set; }
        public int CategoriaId { get; set; }
    
        public virtual CategoriasSet CategoriasSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibroAutorSet> LibroAutorSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibroEjemplarSet> LibroEjemplarSets { get; set; }
    }
}
