//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcLibreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroAutorSet
    {
        public int Id { get; set; }
        public string LibroISBN { get; set; }
        public int AutorId { get; set; }
    
        public virtual AutoresSet AutoresSet { get; set; }
        public virtual LibrosSet LibrosSet { get; set; }
    }
}
